# Generated by Django 4.2.5 on 2023-10-02 23:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_equipment', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('failure', models.TextField(max_length=255)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ServiceOrder', to_field='number')),
            ],
        ),
    ]
